---
title: "MWMB-SART-MindStates-v1"
author: "Elaine P."
date: "2024-06-25"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r} 
rm(list=ls())
#---- Packages ----
library(plyr)
library(dplyr)
library(tidyr)
library(reshape2)
library(stringr)
library(ggplot2)
library(gridExtra)
library(RColorBrewer)
library(lme4)
library(ggpubr)
library(stats)
library(rstatix)
library(ppcor)
library(lme4)
library(lmerTest)
library(tidyverse)
library(data.table)

# ---- Import files -----
#full dataset:
dataset <- read.table('/Users/elaine/Desktop/Git_Studies/MWMB_ADHD/tables/MWMB_ADHD_all_probe_behav.txt', header = TRUE, sep = ",", dec = ".")

# Excluding C015 as they didn't understand instructions:
dataset <- dataset[!dataset$SubID=="C015",]

# To Check how many participants in each group 
num_participants_adhd <- dataset %>%
  filter(Group == "A") %>%
  summarize(num_participants = n_distinct(SubID))

num_participants_control <- dataset %>%
  filter(Group == "C") %>%
  summarize(num_participants = n_distinct(SubID))


```


```{r}
# Changing values of Mind States
dataset <- dataset %>%
  mutate(State = case_when(
    State == 1 ~ "On Task",
    State == 2 ~ "Mind Wandering",
    State == 3 ~ "Mind Blanking",
    State == 4 ~ "Don't Remember"
  ))

# Chi-test on mind states 
mindstates <- table(dataset$Group, dataset$State)

mind_chi <- chisq_test(mindstates)
print(mind_chi)

# Chi test for each mind states
mind_states <- unique(dataset$State)

# Perform chi-square test for each mind state #Commmented out as Thomas said that to look at the specific states, just do a non-parametric test
# for (mind_state in mind_states) {
#   subset_data <- dataset[dataset$State == mind_state, ]
#   
#   # Create a contingency table
#   contingency_table <- table(subset_data$Group)
#   
#   # Perform the chi-square test
#   chi_test <- chisq.test(contingency_table)
#   
#   # Display the test result
#   print(paste("Chi-Square Test Result for", mind_state, ":"))
#   print(chi_test)
# }

```
```{r}
# Changing values of Vigilance
dataset <- dataset %>%
  mutate(Vigilance = case_when(
    Vigilance == 1 ~ "Ex Alert",
    Vigilance == 2 ~ "Alert",
    Vigilance == 3 ~ "Sleepy",
    Vigilance == 4 ~ "Ex Sleepy"
  ))

# Chi-test on mind states 
vigilance <- table(dataset$Group, dataset$Vigilance)

vig_chi <- chisq_test(vigilance)
print(vig_chi)
```
